# Generated by Django 5.2.5 on 2025-11-16 21:40

import datetime
import django.db.models.deletion
import doctorappointment.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authy', '0001_initial'),
        ('hospitalmanagement', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(choices=[('general', 'General'), ('cardiologist', 'Cardiologist'), ('neurologist', 'Neurologist'), ('orthopedist', 'Orthopedist'), ('pediatrician', 'Pediatrician'), ('gynecologist', 'Gynecologist'), ('dermatologist', 'Dermatologist'), ('psychiatrist', 'Psychiatrist'), ('oncologist', 'Oncologist'), ('gastroenterologist', 'Gastroenterologist'), ('pulmonologist', 'Pulmonologist'), ('endocrinologist', 'Endocrinologist'), ('nephrologist', 'Nephrologist'), ('rheumatologist', 'Rheumatologist'), ('ophthalmologist', 'Ophthalmologist'), ('ent specialist', 'Ent Specialist'), ('anesthesiologist', 'Anesthesiologist'), ('radiologist', 'Radiologist'), ('pathologist', 'Pathologist'), ('surgeon', 'Surgeon'), ('sexologist', 'Sexologist'), ('emergency', 'Emergency')], default='general', max_length=50)),
                ('qualification', models.CharField(choices=[('mbbs', 'Mbbs'), ('md', 'Md'), ('ms', 'Ms'), ('dm', 'Dm'), ('mch', 'Mch'), ('diploma', 'Diploma'), ('fellowship', 'Fellowship')], default='mbbs', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.PositiveIntegerField(default=300)),
                ('start_available_days', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10)),
                ('end_available_days', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='friday', max_length=10)),
                ('start_available_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_available_time', models.TimeField(default=datetime.time(17, 0))),
                ('languages_spoken', models.CharField(choices=[('assamese', 'Assamese'), ('bengali', 'Bengali'), ('bodo', 'Bodo'), ('dogri', 'Dogri'), ('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi'), ('kannada', 'Kannada'), ('kashmiri', 'Kashmiri'), ('konkani', 'Konkani'), ('maithili', 'Maithili'), ('malayalam', 'Malayalam'), ('manipuri', 'Manipuri'), ('marathi', 'Marathi'), ('nepali', 'Nepali'), ('odia', 'Odia'), ('punjabi', 'Punjabi'), ('sanskrit', 'Sanskrit'), ('santali', 'Santali'), ('sindhi', 'Sindhi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('urdu', 'Urdu')], default='english', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctors', to='hospitalmanagement.hospital')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='authy.profile')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documents', models.FileField(blank=True, null=True, upload_to=doctorappointment.models.pdf_upload_path)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('waiting_number', models.PositiveIntegerField(default=0)),
                ('bringing_documents', models.TextField(blank=True, null=True)),
                ('visit_fee', models.PositiveIntegerField(default=300)),
                ('appointment_date', models.DateField(default=doctorappointment.models.get_default_date)),
                ('appointment_time', models.TimeField(default=doctorappointment.models.get_default_time)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'confirmed'), ('Reconfirmed', 'reconfirmed'), ('Completed', 'completed'), ('Cancelled', 'cancelled')], default='Pending', max_length=20)),
                ('doctor_updated', models.BooleanField(default=False)),
                ('patient_status_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='authy.profile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='doctorappointment.doctor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_doctor_appointment')],
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(default=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to='doctorappointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authy.profile')),
            ],
            options={
                'verbose_name': 'Doctor Review',
                'verbose_name_plural': 'Doctor Reviews',
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_range', violation_error_message='Rating must be between 1 and 5.'), models.UniqueConstraint(fields=('doctor', 'patient'), name='unique_doctor_patient_review', violation_error_message='A patient can only review a doctor once.')],
            },
        ),
    ]
