import django, os
os.environ['DJANGO_SETTINGS_MODULE'] = 'backend.settings'
django.setup()
from hospitalmanagement.models import Hospital

hospitals = [
    {
        'name': 'Apollo Hospitals',
        'state': 'Tamil Nadu',
        'district': 'Chennai',
        'address': '21, Greams Lane, Off Greams Road, Chennai',
        'pincode': '600006',
        'category': 'private',
        'phone': '04428293333',
        'email': 'info@apollohospitals.com',
        'website': 'https://www.apollohospitals.com',
        'bed_count': 700,
        'established_year': 1983,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
    {
        'name': 'AIIMS New Delhi',
        'state': 'Delhi',
        'district': 'New Delhi',
        'address': 'Sri Aurobindo Marg, Ansari Nagar, New Delhi',
        'pincode': '110029',
        'category': 'government',
        'phone': '01126588500',
        'email': 'director@aiims.edu',
        'website': 'https://www.aiims.edu',
        'bed_count': 2500,
        'established_year': 1956,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
    {
        'name': 'Fortis Memorial Research Institute',
        'state': 'Haryana',
        'district': 'Gurugram',
        'address': 'Sector 44, Gurugram, Haryana',
        'pincode': '122002',
        'category': 'private',
        'phone': '01244962200',
        'email': 'info@fortishealthcare.com',
        'website': 'https://www.fortishealthcare.com',
        'bed_count': 1000,
        'established_year': 2001,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
    {
        'name': 'Medanta - The Medicity',
        'state': 'Haryana',
        'district': 'Gurugram',
        'address': 'CH Baktawar Singh Road, Sector 38, Gurugram',
        'pincode': '122001',
        'category': 'private',
        'phone': '01248834111',
        'email': 'info@medanta.org',
        'website': 'https://www.medanta.org',
        'bed_count': 1600,
        'established_year': 2009,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
    {
        'name': 'CMC Vellore',
        'state': 'Tamil Nadu',
        'district': 'Vellore',
        'address': 'Ida Scudder Road, Vellore, Tamil Nadu',
        'pincode': '632004',
        'category': 'charity',
        'phone': '04162281000',
        'email': 'contact@cmcvellore.ac.in',
        'website': 'https://www.cmch-vellore.edu',
        'bed_count': 2700,
        'established_year': 1900,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
    {
        'name': 'Narayana Health',
        'state': 'Karnataka',
        'district': 'Bangalore',
        'address': '258/A, Bommasandra Industrial Area, Bangalore',
        'pincode': '560099',
        'category': 'private',
        'phone': '08071222222',
        'email': 'info@narayanahealth.org',
        'website': 'https://www.narayanahealth.org',
        'bed_count': 900,
        'established_year': 2000,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': False,
        'parking_available': True,
    },
    {
        'name': 'Manipal Hospitals',
        'state': 'Karnataka',
        'district': 'Bangalore',
        'address': '98, HAL Old Airport Road, Bangalore',
        'pincode': '560017',
        'category': 'private',
        'phone': '08025024444',
        'email': 'info@manipalhospitals.com',
        'website': 'https://www.manipalhospitals.com',
        'bed_count': 600,
        'established_year': 1991,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
    {
        'name': 'Tata Memorial Hospital',
        'state': 'Maharashtra',
        'district': 'Mumbai',
        'address': 'Dr. E Borges Road, Parel, Mumbai',
        'pincode': '400012',
        'category': 'government',
        'phone': '02224177000',
        'email': 'msoffice@tmc.gov.in',
        'website': 'https://tmc.gov.in',
        'bed_count': 800,
        'established_year': 1941,
        'emergency_services': True,
        'ambulance_service': False,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
    {
        'name': 'Kokilaben Dhirubhai Ambani Hospital',
        'state': 'Maharashtra',
        'district': 'Mumbai',
        'address': 'Rao Saheb Achutrao Patwardhan Marg, Andheri West, Mumbai',
        'pincode': '400053',
        'category': 'private',
        'phone': '02230999999',
        'email': 'info@kokilabenhospital.com',
        'website': 'https://www.kokilabenhospital.com',
        'bed_count': 750,
        'established_year': 2009,
        'emergency_services': True,
        'ambulance_service': True,
        'blood_bank': True,
        'pharmacy': True,
        'cafeteria': True,
        'parking_available': True,
    },
]

created = 0
for h in hospitals:
    obj, was_created = Hospital.objects.get_or_create(name=h['name'], defaults=h)
    if was_created:
        created += 1
        print(f'Created: {h["name"]}')
    else:
        print(f'Already exists: {h["name"]}')

print(f'Done. Created {created} new hospitals. Total: {Hospital.objects.count()}')
