# Generated by Django 5.2.5 on 2026-02-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='image_url',
            field=models.URLField(blank=True, help_text='Product image URL', max_length=500, null=True),
        ),
    ]
