# Generated by Django 5.2.5 on 2025-11-16 21:40

import django.db.models.deletion
import hospitalmanagement.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=hospitalmanagement.models.hospital_directory_path)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('category', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('charity', 'Charity')], default='private', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bed_count', models.PositiveIntegerField(default=0)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('emergency_services', models.BooleanField(default=False)),
                ('ambulance_service', models.BooleanField(default=False)),
                ('blood_bank', models.BooleanField(default=False)),
                ('pharmacy', models.BooleanField(default=False)),
                ('cafeteria', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('bed_count__gte', 0)), name='bed_count_validation', violation_error_message='Bed count must be greater than 0 !'), models.CheckConstraint(condition=models.Q(('established_year__gte', 1800), ('established_year__lte', 2025)), name='established_year_validation', violation_error_message='Established year must be between 1800 and current year !'), models.CheckConstraint(condition=models.Q(('pincode__regex', '^\\d{6}$')), name='pincode_validation', violation_error_message='Pincode must be a 6-digit number !')],
            },
        ),
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='hospitalmanagement.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_validation', violation_error_message='Rating must be between 1 and 5!')],
            },
        ),
    ]
