# Generated by Django 5.2.5 on 2026-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hospital',
            name='established_year_validation',
        ),
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.CheckConstraint(condition=models.Q(('established_year__gte', 1800), ('established_year__lte', 2026)), name='established_year_validation', violation_error_message='Established year must be between 1800 and current year !'),
        ),
    ]
